[pytest]
testpaths = tests
pythonpath = .
addopts = -v --tb=short --cov=config.py --cov=controller --cov=entity --cov=middleware --cov=repository --cov=service --cov=utils --cov=main.py --cov-report=term-missing --cov-report=html:coverage_reports/html --cov-fail-under=70
